[build]
# Commande de build pour Angular
command = "npm run build"
# Dossier contenant les fichiers buildés (Angular 17+ structure)
publish = "dist/cthulhu-character-app/browser"

[build.environment]
# Version de Node.js recommandée
NODE_VERSION = "22.x"

# Configuration pour Single Page Application (SPA)
# Redirige toutes les routes vers index.html pour permettre le routing Angular
[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Headers de sécurité et performance
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-Content-Type-Options = "nosniff"
X-XSS-Protection = "1; mode=block"
Referrer-Policy = "strict-origin-when-cross-origin"

# Cache pour les assets statiques
[[headers]]
for = "/assets/*"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

# Cache pour les fichiers JS et CSS avec hash
[[headers]]
for = "/*.js"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
for = "/*.css"
[headers.values]
Cache-Control = "public, max-age=31536000, immutable"
